## dep: Deployments 

apiVersion: apps/v1 ## 'kubectl api-resources'를 터미널에 입력하면 밑의 kind와 매칭되는 버전을 알려줌
kind: Deployment
metadata:
  name: boot001dep
spec:
  # 디플로이먼트 컨트롤러가 인지할ㄹ 파드의 라벨 정보
  selector:
    matchLabels:
      app: boot001kube  # deployment가 인지할 pod의 이름
  replicas: 3           # pod 3개 유지
                        ## 레플리카셋(->3개의 백엔드 컨테이너를 뛰우겠다)

  # 생성 할 파드의 정보
  template:
    metadata:
      labels:
        app: boot001kube  ## spec.selector.matchLabels.app과 일치시켜줘야 한다.
    spec:
      containers:
      - name: boot-container
        image: sg0040/k8s_19_boot:latest # 태깅해야 나중에 k8s에 용이함!
                                          ## !!쿠버네티스할 떄는 태깅을 해줘야 제대로 인식된다!!
        
        # 1. Always: 무조건 Docker Hub에서 이미지를 가져옴
        # 2. IfNotPresent: Local에 없으면 Docker Hub에서 이미지를 가져옴(Local 우선)
        # 3. Never: Local 이미지만 활용(Only Local)
        imagePullPolicy: Always
        ports:
        - containerPort: 7777 ## 내외부가 동일한 포트를 사용(7777:7777)