apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: vue001dep 
spec: 
  selector:
    matchLabels:
      app: vue001kube 
  ## replicas가 생략되면 replicas: 1이 기본적으로 들어감
  template: 
    metadata:
      labels:
        app: vue001kube 
    spec:
      containers:
      - name: vue-container 
        image: sg0040/k8s_19_vue:latest # 태깅해야 나중에 k8s에 용이함!
        imagePullPolicy: Always 
        ports:
        - containerPort: 5173 