apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot002dep
spec:
  selector:
    matchLabels:
      app: boot002kube
  # replicas: 3
  replicas: 1
  template:
    metadata:
      labels:
        app: boot002kube
    spec:
      containers:
      - name: boot-container
        image: sg0040/k8s_19_boot2:latest
        imagePullPolicy: Always   ## docker hub에 있는 것을ㄹㄹ 가져온다.
        ports:
        - containerPort: 7777